### ISSUE TITLE
CLI doesn't work if installed via `npm`

### ISSUE THREAD

**Issue by jakerdy** [tinyhttp/cli#2]
**Describe the bug**

I am working on windows. I've tried to create new project with CLI, and it failed.

My setup:
- npm 9.6.7
- git bash for windows (it comes with git distribution for windows)
- node 18.17.0

0. `Git Bash Here` from context menu in a directory with my projects
1. npm i -g @tinyhttp/cli
2. tinyhttp new basic my-app
3. it fails with:
```bash
C:\Users\JE\AppData\Roaming\npm/node_modules/@tinyhttp/cli/dist/index.js: line 1: import: command not found
C:\Users\JE\AppData\Roaming\npm/node_modules/@tinyhttp/cli/dist/index.js: line 2: import: command not found
C:\Users\JE\AppData\Roaming\npm/node_modules/@tinyhttp/cli/dist/index.js: line 3: import: command not found
C:\Users\JE\AppData\Roaming\npm/node_modules/@tinyhttp/cli/dist/index.js: line 4: import: command not found
C:\Users\JE\AppData\Roaming\npm/node_modules/@tinyhttp/cli/dist/index.js: line 5: import: command not found
C:\Users\JE\AppData\Roaming\npm/node_modules/@tinyhttp/cli/dist/index.js: line 6: import: command not found
C:\Users\JE\AppData\Roaming\npm/node_modules/@tinyhttp/cli/dist/index.js: line 7: import: command not found
C:\Users\JE\AppData\Roaming\npm/node_modules/@tinyhttp/cli/dist/index.js: line 8: import: command not found
C:\Users\JE\AppData\Roaming\npm/node_modules/@tinyhttp/cli/dist/index.js: line 9: import: command not found
C:\Users\JE\AppData\Roaming\npm/node_modules/@tinyhttp/cli/dist/index.js: line 11: syntax error near unexpected token `('
C:\Users\JE\AppData\Roaming\npm/node_modules/@tinyhttp/cli/dist/index.js: line 11: `const msg = (m, color) => console.log(colorette[color](m));'
```

Also, if i try to run `tinyhttp new...` from cmd of powershell, I got cli index.js opened in default editor for .js files. Is it me, or CLI shouldn't work on Windows?

**Expected behavior**

It should work as described in tutorial. I want to get working and settuped project to avoid all that ESM hustle...

**Comment by talentlessguy** [comment]
@jakerdy could you test on latest 1.3.5 please?

**Comment by talentlessguy** [comment]
@jakerdy shit, I'm sorry I convert the readme to JSON and that's why it breaks

**Comment by talentlessguy** [comment]
will release a patch soon

**Comment by talentlessguy** [comment]
@jakerdy could you try please on latest version? sorry for a late response

**Comment by jakerdy** [comment]
Nope, it still doesn't work.
![image](https://github.com/tinyhttp/cli/assets/66637406/bc8870dc-e08b-43f3-8398-49753908ffe4)

**Comment by aarontravass** [comment]
@talentlessguy

**Comment by talentlessguy** [comment]
@jakerdy sorry for the delay again - i've published a new version, it should work properly now
